# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=64, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_type', models.CharField(choices=[('PC', 'Кошелек Яндекс.Деньги'), ('AC', 'Банковская карта'), ('GP', 'Наличными через кассы и терминалы'), ('MC', 'Счет мобильного телефона'), ('WM', 'Кошелек WebMoney'), ('SB', 'Сбербанк: оплата по SMS или Сбербанк Онлайн'), ('AB', 'Альфа-Клик'), ('MA', 'MasterPass'), ('PB', 'Интернет-банк Промсвязьбанка'), ('QW', 'QIWI Wallet'), ('QP', 'Доверительный платеж (Куппи.ру)')], default='PC', max_length=2)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('hold', 'Hold'), ('cancel', 'Cancel'), ('success', 'Success'), ('fail', 'Fail')], default='processed', max_length=16, verbose_name='Результата')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('performed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created',),
            },
        ),
    ]
