# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('h2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('action_title', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='common/sliders/')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Слайдер на главной странице',
                'verbose_name_plural': 'Слайдер на главной странице',
                'ordering': ('position',),
            },
        ),
    ]
