# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170528_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
