# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='take_date',
            field=models.DateField(null=True),
        ),
    ]
