# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20170424_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date_return',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date_take',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
