# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20170424_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='order',
            new_name='basket',
        ),
    ]
