# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20170427_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('woman', 'Женский')], default='male', max_length=20),
        ),
    ]
