# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_line_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ('pk',), 'verbose_name': 'Строка корзины', 'verbose_name_plural': 'Строки корзины'},
        ),
        migrations.AddField(
            model_name='basket',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
