# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20170428_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
