# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20170428_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
