# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170618_0458'),
        ('basket', '0010_basket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Size'),
        ),
    ]
